### ISSUE TITLE
Add support for an enable secret argument (test if this works properly).

### ISSUE THREAD

**Issue by ktbyers** [ktbyers/netsidecar#8]

**Comment by shahid2704** [comment]
hello,
i am getting the below error.Can you please help me fix this.
Traceback (most recent call last):
  File "C:/Upgrade.py", line 3, in <module>
  from ansible.module_utils.basic import *
  File "C:\Anaconda\lib\site-packages\ansible\module_utils\basic.py", line 78, in <module>
    import grp
ModuleNotFoundError: No module named 'grp'
